/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Objects.Employee;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import libraryFunctions.repository;

/**
 *
 * @author aocar
 */
public class newEmployee extends javax.swing.JFrame {

    /**
     * Creates new form newEmployee
     */
    public newEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        createEmployeeButton = new javax.swing.JButton();
        hireDateText = new javax.swing.JTextField();
        snameText = new javax.swing.JTextField();
        fnameText = new javax.swing.JTextField();
        employeeIDText = new javax.swing.JTextField();
        passText = new javax.swing.JTextField();
        officeText = new javax.swing.JTextField();
        departmentText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        hourlyRateText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Employee ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(128, 100, 88, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(128, 140, 74, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(128, 180, 73, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Employee Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(128, 220, 138, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Department");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(128, 300, 83, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Office");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(128, 260, 39, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(128, 340, 104, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Hire Date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(128, 380, 64, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Hourly Rate");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(128, 420, 82, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("New Employee");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 30, 102, 17);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(128, 500, 55, 23);

        createEmployeeButton.setText("Create Employee");
        createEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createEmployeeButton);
        createEmployeeButton.setBounds(570, 500, 140, 23);

        hireDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hireDateTextActionPerformed(evt);
            }
        });
        getContentPane().add(hireDateText);
        hireDateText.setBounds(360, 380, 130, 28);

        snameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameTextActionPerformed(evt);
            }
        });
        getContentPane().add(snameText);
        snameText.setBounds(360, 180, 130, 28);

        fnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTextActionPerformed(evt);
            }
        });
        getContentPane().add(fnameText);
        fnameText.setBounds(360, 140, 130, 28);

        employeeIDText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employeeIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIDTextActionPerformed(evt);
            }
        });
        getContentPane().add(employeeIDText);
        employeeIDText.setBounds(360, 100, 130, 28);

        passText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextActionPerformed(evt);
            }
        });
        getContentPane().add(passText);
        passText.setBounds(360, 220, 130, 28);

        officeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeTextActionPerformed(evt);
            }
        });
        getContentPane().add(officeText);
        officeText.setBounds(360, 260, 130, 28);

        departmentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentTextActionPerformed(evt);
            }
        });
        getContentPane().add(departmentText);
        departmentText.setBounds(360, 300, 130, 28);

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });
        getContentPane().add(phoneText);
        phoneText.setBounds(360, 340, 130, 28);

        hourlyRateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateTextActionPerformed(evt);
            }
        });
        getContentPane().add(hourlyRateText);
        hourlyRateText.setBounds(360, 420, 130, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Personnel_Menu PMenu = new Personnel_Menu();
        PMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void createEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeButtonActionPerformed

        try{

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate Employee_HireDate = LocalDate.parse(hireDateText.getText(), formatter);
            double Employee_HourlyRate;

            Employee newEmployee = new Employee (employeeIDText.getText(),fnameText.getText(),snameText.getText(),passText.getText(),departmentText.getText(),officeText.getText(),phoneText.getText(),Date.valueOf(Employee_HireDate),Double.parseDouble(hourlyRateText.getText()));
            
            repository.insertNewEmployee(newEmployee);
            
            JOptionPane.showMessageDialog(null, "New employee added successfully");
            MainMenu main = new MainMenu();
            main.setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            System.out.println("Error in NewEmployee form" + e);
        }
    }//GEN-LAST:event_createEmployeeButtonActionPerformed

    private void hireDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hireDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hireDateTextActionPerformed

    private void snameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameTextActionPerformed

    private void fnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTextActionPerformed

    private void employeeIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIDTextActionPerformed

    private void passTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextActionPerformed

    private void officeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officeTextActionPerformed

    private void departmentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentTextActionPerformed

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextActionPerformed

    private void hourlyRateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createEmployeeButton;
    private javax.swing.JTextField departmentText;
    private javax.swing.JTextField employeeIDText;
    private javax.swing.JTextField fnameText;
    private javax.swing.JTextField hireDateText;
    private javax.swing.JTextField hourlyRateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField officeText;
    private javax.swing.JTextField passText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTextField snameText;
    // End of variables declaration//GEN-END:variables
}
